// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Parts is the golang structure of table parts for DAO operations like Where/Data.
type Parts struct {
	g.Meta     `orm:"table:parts, do:true"`
	Id         interface{} //
	TaskId     interface{} //
	PartNum    interface{} //
	ContentMd5 interface{} //
	Etag       interface{} //
	Status     interface{} //
}
