// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Tasks is the golang structure of table tasks for DAO operations like Where/Data.
type Tasks struct {
	g.Meta     `orm:"table:tasks, do:true"`
	Id         interface{} //
	UploadId   interface{} //
	BucketName interface{} //
	FileKey    interface{} //
	Src        interface{} //
	CreatedAt  interface{} //
}
