// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/steemfans/multiple-upload-to-s3/internal/dao/internal"
)

// internalPartsDao is internal type for wrapping internal DAO implements.
type internalPartsDao = *internal.PartsDao

// partsDao is the data access object for table parts.
// You can define custom methods on it to extend its functionality as you wish.
type partsDao struct {
	internalPartsDao
}

var (
	// Parts is globally public accessible object for table parts operations.
	Parts = partsDao{
		internal.NewPartsDao(),
	}
)

// Fill with you ideas below.
