// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Parts is the golang structure for table parts.
type Parts struct {
	Id         int    `json:"id"         ` //
	TaskId     int    `json:"taskId"     ` //
	PartNum    int    `json:"partNum"    ` //
	ContentMd5 string `json:"contentMd5" ` //
	Etag       string `json:"etag"       ` //
	Status     int    `json:"status"     ` //
}
