// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Tasks is the golang structure for table tasks.
type Tasks struct {
	Id         int    `json:"id"         ` //
	PartId     string `json:"partId"     ` //
	BucketName string `json:"bucketName" ` //
	FileKey    string `json:"fileKey"    ` //
	Src        string `json:"src"        ` //
	CreatedAt  string `json:"createdAt"  ` //
}
